export interface Cid10Entry {
  code: string;
  label: string;
  group: string;
}

export const CID10_MENTAL_HEALTH: Cid10Entry[] = [
  { code: 'F00', label: 'Demência na doença de Alzheimer', group: 'Transtornos mentais orgânicos' },
  { code: 'F01', label: 'Demência vascular', group: 'Transtornos mentais orgânicos' },
  { code: 'F02', label: 'Demência em outras doenças classificadas em outra parte', group: 'Transtornos mentais orgânicos' },
  { code: 'F03', label: 'Demência não especificada', group: 'Transtornos mentais orgânicos' },
  { code: 'F04', label: 'Síndrome amnésica orgânica não induzida por álcool ou substâncias psicoativas', group: 'Transtornos mentais orgânicos' },
  { code: 'F05', label: 'Delirium não induzido por álcool ou substâncias psicoativas', group: 'Transtornos mentais orgânicos' },
  { code: 'F06', label: 'Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física', group: 'Transtornos mentais orgânicos' },
  { code: 'F07', label: 'Transtornos de personalidade e comportamento devidos a doença, lesão e disfunção cerebral', group: 'Transtornos mentais orgânicos' },
  { code: 'F09', label: 'Transtorno mental orgânico ou sintomático não especificado', group: 'Transtornos mentais orgânicos' },
  { code: 'F10', label: 'Transtornos mentais e comportamentais devidos ao uso de álcool', group: 'Uso de substâncias' },
  { code: 'F11', label: 'Transtornos mentais e comportamentais devidos ao uso de opiáceos', group: 'Uso de substâncias' },
  { code: 'F12', label: 'Transtornos mentais e comportamentais devidos ao uso de canabinoides', group: 'Uso de substâncias' },
  { code: 'F13', label: 'Transtornos mentais e comportamentais devidos ao uso de sedativos e hipnóticos', group: 'Uso de substâncias' },
  { code: 'F14', label: 'Transtornos mentais e comportamentais devidos ao uso de cocaína', group: 'Uso de substâncias' },
  { code: 'F15', label: 'Transtornos mentais e comportamentais devidos ao uso de outros estimulantes', group: 'Uso de substâncias' },
  { code: 'F16', label: 'Transtornos mentais e comportamentais devidos ao uso de alucinógenos', group: 'Uso de substâncias' },
  { code: 'F17', label: 'Transtornos mentais e comportamentais devidos ao uso de fumo', group: 'Uso de substâncias' },
  { code: 'F18', label: 'Transtornos mentais e comportamentais devidos ao uso de solventes voláteis', group: 'Uso de substâncias' },
  { code: 'F19', label: 'Transtornos mentais e comportamentais devidos ao uso de múltiplas drogas e outras substâncias psicoativas', group: 'Uso de substâncias' },
  { code: 'F20', label: 'Esquizofrenia', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F21', label: 'Transtorno esquizotípico', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F22', label: 'Transtornos delirantes persistentes', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F23', label: 'Transtornos psicóticos agudos e transitórios', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F24', label: 'Transtorno delirante induzido', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F25', label: 'Transtornos esquizoafetivos', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F28', label: 'Outros transtornos psicóticos não-orgânicos', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F29', label: 'Psicose não-orgânica não especificada', group: 'Esquizofrenia e transtornos delirantes' },
  { code: 'F30', label: 'Episódio maníaco', group: 'Transtornos do humor' },
  { code: 'F31', label: 'Transtorno afetivo bipolar', group: 'Transtornos do humor' },
  { code: 'F32', label: 'Episódios depressivos', group: 'Transtornos do humor' },
  { code: 'F32.0', label: 'Episódio depressivo leve', group: 'Transtornos do humor' },
  { code: 'F32.1', label: 'Episódio depressivo moderado', group: 'Transtornos do humor' },
  { code: 'F32.2', label: 'Episódio depressivo grave sem sintomas psicóticos', group: 'Transtornos do humor' },
  { code: 'F32.3', label: 'Episódio depressivo grave com sintomas psicóticos', group: 'Transtornos do humor' },
  { code: 'F32.9', label: 'Episódio depressivo não especificado', group: 'Transtornos do humor' },
  { code: 'F33', label: 'Transtorno depressivo recorrente', group: 'Transtornos do humor' },
  { code: 'F34', label: 'Transtornos de humor persistentes', group: 'Transtornos do humor' },
  { code: 'F38', label: 'Outros transtornos do humor', group: 'Transtornos do humor' },
  { code: 'F39', label: 'Transtorno do humor não especificado', group: 'Transtornos do humor' },
  { code: 'F40', label: 'Transtornos fóbico-ansiosos', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F40.0', label: 'Agorafobia', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F40.1', label: 'Fobias sociais', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F40.2', label: 'Fobias específicas', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F41', label: 'Outros transtornos ansiosos', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F41.0', label: 'Transtorno de pânico', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F41.1', label: 'Ansiedade generalizada', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F41.2', label: 'Transtorno misto ansioso e depressivo', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F42', label: 'Transtorno obsessivo-compulsivo', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F43', label: 'Reações ao estresse grave e transtornos de adaptação', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F43.0', label: 'Reação aguda ao estresse', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F43.1', label: 'Estado de estresse pós-traumático', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F43.2', label: 'Transtornos de adaptação', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F44', label: 'Transtornos dissociativos', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F45', label: 'Transtornos somatoformes', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F48', label: 'Outros transtornos neuróticos', group: 'Ansiedade, estresse e somatoformes' },
  { code: 'F50', label: 'Transtornos da alimentação', group: 'Síndromes comportamentais' },
  { code: 'F51', label: 'Transtornos não-orgânicos do sono', group: 'Síndromes comportamentais' },
  { code: 'F52', label: 'Disfunção sexual não causada por transtorno ou doença orgânica', group: 'Síndromes comportamentais' },
  { code: 'F53', label: 'Transtornos mentais e comportamentais associados ao puerpério', group: 'Síndromes comportamentais' },
  { code: 'F54', label: 'Fatores psicológicos associados a doenças classificadas em outra parte', group: 'Síndromes comportamentais' },
  { code: 'F55', label: 'Abuso de substâncias que não produzem dependência', group: 'Síndromes comportamentais' },
  { code: 'F59', label: 'Síndromes comportamentais não especificadas associadas a perturbações fisiológicas', group: 'Síndromes comportamentais' },
  { code: 'F60', label: 'Transtornos específicos da personalidade', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.0', label: 'Personalidade paranoica', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.1', label: 'Personalidade esquizoide', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.2', label: 'Personalidade dissocial', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.3', label: 'Transtorno de personalidade com instabilidade emocional', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.4', label: 'Personalidade histriônica', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.5', label: 'Personalidade anancástica', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.6', label: 'Personalidade ansiosa/esquiva', group: 'Personalidade e comportamento adulto' },
  { code: 'F60.7', label: 'Personalidade dependente', group: 'Personalidade e comportamento adulto' },
  { code: 'F61', label: 'Transtornos mistos da personalidade', group: 'Personalidade e comportamento adulto' },
  { code: 'F62', label: 'Modificações duradouras da personalidade não atribuíveis a lesão cerebral', group: 'Personalidade e comportamento adulto' },
  { code: 'F63', label: 'Transtornos dos hábitos e dos impulsos', group: 'Personalidade e comportamento adulto' },
  { code: 'F64', label: 'Transtornos da identidade sexual', group: 'Personalidade e comportamento adulto' },
  { code: 'F65', label: 'Transtornos da preferência sexual', group: 'Personalidade e comportamento adulto' },
  { code: 'F66', label: 'Transtornos psicológicos e comportamentais associados ao desenvolvimento sexual', group: 'Personalidade e comportamento adulto' },
  { code: 'F68', label: 'Outros transtornos da personalidade e do comportamento adulto', group: 'Personalidade e comportamento adulto' },
  { code: 'F69', label: 'Transtorno da personalidade e do comportamento adulto não especificado', group: 'Personalidade e comportamento adulto' },
  { code: 'F70', label: 'Retardo mental leve', group: 'Desenvolvimento e infância' },
  { code: 'F71', label: 'Retardo mental moderado', group: 'Desenvolvimento e infância' },
  { code: 'F72', label: 'Retardo mental grave', group: 'Desenvolvimento e infância' },
  { code: 'F73', label: 'Retardo mental profundo', group: 'Desenvolvimento e infância' },
  { code: 'F78', label: 'Outro retardo mental', group: 'Desenvolvimento e infância' },
  { code: 'F79', label: 'Retardo mental não especificado', group: 'Desenvolvimento e infância' },
  { code: 'F80', label: 'Transtornos específicos do desenvolvimento da fala e da linguagem', group: 'Desenvolvimento e infância' },
  { code: 'F81', label: 'Transtornos específicos do desenvolvimento das habilidades escolares', group: 'Desenvolvimento e infância' },
  { code: 'F82', label: 'Transtorno específico do desenvolvimento motor', group: 'Desenvolvimento e infância' },
  { code: 'F83', label: 'Transtornos específicos mistos do desenvolvimento', group: 'Desenvolvimento e infância' },
  { code: 'F84', label: 'Transtornos globais do desenvolvimento', group: 'Desenvolvimento e infância' },
  { code: 'F84.0', label: 'Autismo infantil', group: 'Desenvolvimento e infância' },
  { code: 'F84.5', label: 'Síndrome de Asperger', group: 'Desenvolvimento e infância' },
  { code: 'F88', label: 'Outros transtornos do desenvolvimento psicológico', group: 'Desenvolvimento e infância' },
  { code: 'F89', label: 'Transtorno do desenvolvimento psicológico não especificado', group: 'Desenvolvimento e infância' },
  { code: 'F90', label: 'Transtornos hipercinéticos', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F90.0', label: 'Distúrbios da atividade e da atenção', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F90.1', label: 'Transtorno hipercinético de conduta', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F91', label: 'Distúrbios de conduta', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F92', label: 'Transtornos mistos de conduta e emoções', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F93', label: 'Transtornos emocionais com início específico na infância', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F94', label: 'Transtornos do funcionamento social com início específico na infância ou adolescência', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F95', label: 'Tiques', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F98', label: 'Outros transtornos comportamentais e emocionais com início na infância e adolescência', group: 'Transtornos emocionais/comportamentais da infância' },
  { code: 'F99', label: 'Transtorno mental não especificado', group: 'Transtornos não especificados' },
];
