// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createSupabaseAuthStorage } from '@/lib/native-mobile-security';
import { SUPABASE_ANON_KEY, SUPABASE_URL } from '@/lib/supabase-config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: createSupabaseAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
